### ISSUE TITLE
OnPremiseConnector crash

### ISSUE THREAD

**Issue by snapde** [thinktecture/relayserver#11]
Debug from console:

`
2016-08-19` 11:03:38.5039 DEBUG Sending reponse from http://localhost:6913/ to relay
Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.NotSupportedException: Unbekanntes URI-Präfix.
   bei System.Net.WebRequest.CreateHttp(Uri requestUri)
   bei Thinktecture.Relay.OnPremiseConnector.OnPremiseTarget.OnPremiseTargetConnector.<CreateOnPremiseTargetWebRequestAsync>d__10.MoveNext() in .relayserver\Thinktecture.Relay.OnPremiseConnector\OnPremiseTarget\OnPremiseTargetConnector.cs:Zeile 127.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Thinktecture.Relay.OnPremiseConnector.OnPremiseTarget.OnPremiseTargetConnector.<GetResponseAsync>d__9.MoveNext() in .\relayserver\Thinktecture.Relay.OnPremiseConnector\OnPremiseTarget\OnPremiseTargetConnector.cs:Zeile 61.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<RequestOnPremiseTargetAsync>d__33.MoveNext() in .\relayserver\Thinktecture.Relay.OnPremiseConnector\SignalR\RelayServerConnection.cs:Zeile 268.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<OnReceived>d__29.MoveNext() in .\relayserver\Thinktecture.Relay.OnPremiseConnector\SignalR\RelayServerConnection.cs:Zeile 219.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
2016-08-19 11:03:39.1569 TRACE Received message from server: data={
  "RequestId": "58816d0a-6c83-4052-8a6a-f2fc77e688cc",
  "HttpMethod": "GET",
  "Url": "skm/listhttp:/52.166.146.89:20000/relay/asass/skm/list",
  "HttpHeaders": {
    "Origin": "http://localhost:8030",
    "Accept": "_/_",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US, en; q=0.8, de; q=0.6",
    "Authorization": "Bearer eyJ0e...",
    "Referer": "http://localhost:8030/",
    "User-Agent": "Mozilla/5.0, (iPhone; CPU iPhone OS 9_1 like Mac OS X), Apple
WebKit/601.1.46, (KHTML, like Gecko), Version/9.0, Mobile/13B143, Safari/601.1",

```
"Content-Length": "0"
```

  },
  "Body": null,
  "OriginId": "aa277d56-9f2d-4b82-bf50-5dd8f8c279a4"
}`

**Comment by thomashilzendegen** [comment]
It seems that the request url

"Url": "skm/listhttp:/52.166.146.89:20000/relay/asass/skm/list",

is malformed. But indeed, it should not crash then. :)

**Comment by gingters** [comment]
Could not reproduce this issue any more with current development state.
