### ISSUE TITLE
Error message is misleading, if config is not found

### ISSUE THREAD

**Issue by ManuelRauber** [thinktecture/relayserver#122]
### Actual behavior

If the RelayServer is tried to be run out of box, the following error message pops up:

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/740791/49040274-5c57af80-f1c2-11e8-85ca-b1bcfe33896c.png">

To be clear, to get the full size message log, you have to enable FusionLog within the registry. Otherwise you just get the message, that a DLL could not be found.

### Expected behavior

Even though the documentation states, that the configuration file needs to be created, the error message should be more clear, that the config file is missing.

### Steps to reproduce

Unzip RelayServer.zip and run it.

### Version

master, V2

**Comment by thomashilzendegen** [comment]
Fixed in 
https://github.com/thinktecture/relayserver/pull/127
