### ISSUE TITLE
Potentially separate timeouts of OPC to relay and on-premise target

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#125]
At the moment, the OPC (`RelayServerConnection`) uses the same `requestTimeout` configuration value for both the http requests to the RelayServer (posting responses) and for the requests to the on-premise targets.

We probably should separate these into two distinct settings, where the timeout for the relay server requests should be set on the OPC side, and the timeout for the local target requests should be equal to a bit less than the timeout set on the RelayServer for that specific link.

Also validate, if having a single timeout for all Relay server <--> OPC communications makes sense, or if it would be better to be able to have separate timeouts per link.

**Comment by thomashilzendegen** [comment]
Closing due to the release of RelayServer 3.0.0, because no further development is done in the previous version anymore.
