### ISSUE TITLE
Applying RabbitMQ management plugin screenshot shows failed

### ISSUE THREAD

**Issue by SteffenJahr** [thinktecture/relayserver#13]
The screenshot of the RabbitMQ installation shows that enabling of the management plugin failed.

**Comment by ManuelRauber** [comment]
@marcofrodl Can you take a look at it?

**Comment by gingters** [comment]
Issue still is there. See:
https://github.com/thinktecture/relayserver/blob/master/Documentation/de/3-installation.md#rabbitmq-mit-erlang-ausführungsumgebung

and 
https://github.com/thinktecture/relayserver/blob/master/Documentation/en/3-installation.md#rabbitmq-with-erlang-execution-environment
