### ISSUE TITLE
Sample config is not equal to the documentation

### ISSUE THREAD

**Issue by SteffenJahr** [thinktecture/relayserver#14]
Sample config is not equal to the documentation. In example there are different connection strings.

**Comment by gingters** [comment]
Also related to this: #6 

> Documentation states that SSL is on by default.
> Default config that is released however has SSL disabled (which should not be case).

**Comment by gingters** [comment]
This is resolved in the 2.0 release by now.
We documented all settings including their default values and the default config now also explicitely states the default values.
