### ISSUE TITLE
Decrease connection timeout of RabbitMq subscription

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#143]
When a link connects, the server creates a queue subscription for that link id request queue.

When the server crashes, it is possible that rabbit mq does not recognize the failure of the subscriptions connection immidiately. In this case, it still thinks the subscription is active for the time configured as `connection timeout` on the rabbit mq connection.

The default value for that is 60 seconds. So the rabbitmq will try to heartbeat the connection every timeout/2 (=30) seconds, and after 2 subsequent failed heartbeat it will remove the connection.

For these 60 seconds, all requests for that subscriber will still be delivered to the - now dead - server, and not be processed.

We should make the timeout configurable, with a much smaller timeout value as default, and set it on the `RabbitMQ.Client.ConnectionFactory`.

We only put the class in the DI, so we have to set the value manually when registering the type in the DI in the oncreated callback.

Also check, if we are going to handle this as a bug or not.

**Comment by gingters** [comment]
Ideally, set the connection timeout for the rabbit client to 1/4 of the request timeout, so that rabbit has
a) a chance to detect the lost connection early enough and
b) redeliver the request message to the next subscriber in case of multiple connections for a link

**Comment by thomashilzendegen** [comment]
Closing due to the release of RelayServer 3.0.0, because no further development is done in the previous version anymore.
