### ISSUE TITLE
Reconnect required when SignalR connection is dead from the start

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#144]
*Experienced behavior*

OPC connects to RelayServer, but the SignalR connection is immediately dead.

RelayServer does sends its server configuration, heartbeats and pings to the OPC, but on the OPC side nothing gets received through SignalR.

OPC does not initiate heartbeat interval & disconnect check since the initial heartbeat does not arrive.
OPC stays connected forever on the dead connection

*Expected behavior*

If the OPC does not receive a ping or a heartbeat in the first XX (to discuss) seconds after creating a connection, it should immediately try to reconnect.

**Comment by gingters** [comment]
Additional information:
This only happens in the current environment when there is a Citrix Netscaler in front of the RelayServer and 2 Relay server nodes are configured.
As soon as any one of the two nodes is removed from the pool of available machines in the Netscaler, the connections are created and the client immediately receives the SignalR messages.

**Comment by siorpaesas** [comment]
Is there a way to fix this? If not directly in the software itself, is there a workaround to get this working?

Thank you

**Comment by gingters** [comment]
Not so far. Sadly we can't really investigate this issue further, for multiple reasons. The main reason being that we do not have a Citrix Netscaler to create an isolated environment to really track down what that thing does with the connection.

There is also not an easy workaround possible within the On-Premises Connector and the RelayServer. We need to stay backwards compatible with older versions of OPCs that connect to a newer RelayServer as well as newer OPCs that connect to older RelayServers.

An OPC sadly can't tell the difference between connecting to an older RelayServer that does not support heartbeats or server-side configuration, and as such does not send data back to the OPC directly after connecting at all, or if it connected to a newer RelayServer that did send this data through the connection, but the messages never reach the OPC because of the NetScaler in between.

So a possible solution could be to introduce a new RelayServer version that provides an additional endpoint for newer OPCs to exactly determine the version of the RelayServer before establishing the SignalR connection. If the OPC knows that this is a newer server, it also knows that it should receive a heartbeat message shortly after connecting, and could reconnect if that does arrive after a short timeout. If it receives a 404 Not Found on the new version endpoint, it knows its an older server and would not reconnect.

However I sadly can't tell you when we'll be able to extend the RelayServer with that. Maybe contact @marcofrodl for further details and our roadmap :)

**Comment by gingters** [comment]
As an additional remark: Allthough this would allow the OPC to reconnect until it has a stable connection, the main issue with the NetScaler still is there, and this is massive.

The last time I looked at this we had about 1 successful connect in 20 or so that did _not_ work.

So this "workaround" will definetly lead to _a lot_ of unsuccessful connection attempts and hammer the RelayServer with short-lived SignalR connections, whereby I don't know if the server will be able to clean them up after the client disconnects, as the connection is already broken and the RelayServer probably won't be able to detect the disconnect.

There is a possibility that this workaround could lead to an connection overflow on the RelayServer and render it completely unusable until the server will be rebootet.

**Comment by siorpaesas** [comment]
Hello @gingters 

Thank you for your explanation. At least, this will give us a solid base to explain the situation to our customer.
Of course, we will try to find a solution and report here, should we find anything.
