### ISSUE TITLE
Possible issue with too many database connections

### ISSUE THREAD

**Issue by jasminsehic** [thinktecture/relayserver#145]
### Actual behavior
The number of database connections used in the database connection pool steadily grows during the life if RelayServer application and doesn't seem to reduce. We currently have around active 450 links connecting to one SQL server database (and about 1900 dormant links) and I am seeing the number of open connections in the pool reach 300 within about 7 days which is our limit. 
![relayserver_db_connections](https://user-images.githubusercontent.com/3346727/57995560-56011b00-7af5-11e9-9fff-0f96eaf5e97e.PNG)
At the point where the pool is exhausted the RelayServer fails to function properly and requires a restart to get it up and running again.

### Expected behavior
I expected the database connection pool to be re-used and not exceed 300 with 450 active clients, I am unsure now if there is a persistent database connection open for each link all the time or are these connections just transient, it is hard to tell.

### Steps to reproduce
Setup RelayServer on SQL Server 2017 with 450 active links (connecting) and another 1900 inactive links (not connecting) and monitor open database connections on SQL Server, growing each day and never reducing.

### Version
v2.2.0.0

> master, develop, commit-hash, ...

master

**Comment by jasminsehic** [comment]
7 days after restarting RelayServer service you can steadily see the open database connections growing. The number of connected (active) RelayServer clients hovers between 450-470 clients.
![image](https://user-images.githubusercontent.com/3346727/58389531-e8596f80-805d-11e9-8dc9-8c24e279b5a4.png)

**Comment by jasminsehic** [comment]
Number of open SQL database connections in the pool has grown now beyond active links based on `LastActivity` in `ActiveConnections` table.

**Comment by jasminsehic** [comment]
It looks like all the connection sessions are active so there are no leaks. Last SQL executed is in all active sessions is:

`(@p__linq__0 nvarchar(4000))SELECT TOP (1)       [Extent1].[LinkId] AS [LinkId],       [Extent1].[ConnectionId] AS [ConnectionId],       [Extent1].[OriginId] AS [OriginId],       [Extent1].[ConnectorVersion] AS [ConnectorVersion],       [Extent1].[AssemblyVersion] AS [AssemblyVersion],       [Extent1].[LastActivity] AS [LastActivity]      FROM [dbo].[ActiveConnections] AS [Extent1]      WHERE [Extent1].[ConnectionId] = @p__linq__0`

This is used in `RenewActiveConnectionAsync()` and `RemoveActiveConnectionAsync()`, From log files I can see that this is mostly coming from connectors that are failing to authenticate after a RelayServer server upgrade, seeing over 6 million failed authentication requests in last 24 hours which is creating pressure on the database connection pool. 

So this issue seems to largely be a symptom of issue #134 which the branch `bugfix/brokenConnections` fixes. Any ETA on when this fix may be merged and released @gingters?

**Comment by gingters** [comment]
Sorry for the delay, we're a bit behind here.

So, just for my understanding: The issue with too many database connections does not occur when the `bugfix/brokenConnections` branch is integrated?

I can't say when this will happen, but I will ask my colleagues to review the change and approve the corresponding PR which I will create now.

**Comment by jasminsehic** [comment]
Thank you @gingters. 
You are correct, with creating a ConnectionLeaseTimeout with ServicePointManager makes sure that any stale HttpClient connections in the pool are closed which allows on-premise connectors to re-connect and authenticate after we upgrade the RelayServer EC2 instance behind a load balancer. Without this we get up to 200-300 links failing to authenticate on every EC2 upgrade, then they continue to retry again between every 2 to 30 seconds until the on-premise connector process is recycled.

**Comment by EbenZhang** [comment]
Just FYI, I'm from the same company as Jasmin
It's due to the issue `Connections get deactivated over and over` solved in #213
