### ISSUE TITLE
Management web application should be called "Management Web" in the docs

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/relayserver#159]
See https://github.com/thinktecture/relayserver/blob/master/Documentation/en/relayserver.md and https://github.com/thinktecture/relayserver/blob/master/Documentation/en/4-relayserver-web-management.md

The management web application should be called "Management Web", not "Web Management"

**Comment by gingters** [comment]
Good catch 😅

**Comment by gingters** [comment]
Fix has been merged and will be released with 2.3.0 soon-ish. Closing here.
