### ISSUE TITLE
Can we send data from On Premise to Cloud ?

### ISSUE THREAD

**Issue by Sudhanshus2020** [thinktecture/relayserver#160]
### Question
Can we send data from OnPremise to Cloud, **without any request received from cloud** ?

We have a problem where we want to send data from OnPremise to Cloud periodically on the decided frequency (Let's say after every 30 mins) and it is huge data (50,000 records per day).

**Comment by gingters** [comment]
Good Mornung @Sudhanshus2020,

I don't really understand why you ask that specifically for RelayServer.

As long as your OnPrem has an active internet connection, you can send any data at any to any cloud provider without RelayServer. You just send it directly.

**Comment by gingters** [comment]
Closing this since we didn't hear back anything. Feel free to reopen if you have further questions regarding this or create new issues for other questions.
