### ISSUE TITLE
OnPremiseWebTargetConnector does not forward cookies

### ISSUE THREAD

**Issue by borgiman** [thinktecture/relayserver#224]
### Actual behavior
When relaying a request with a cookie via RelayServer and On-Premise Connector the cookie is not received at the On-Premise application, despite the On-Premise Connector log stating otherwise.

### Expected behavior
Cookies that are sent through the On-Premise Connector are relayed to the On-Premise application.

### Steps to reproduce
- Set up a Relay Server
- Set up a OnPremise Connector that relays to application X
- Send a request with a cookie via Relay Server
- Check if the cookie is received by application X

### Version
master, zip downloaded at 20.04.

### Analysis
When disabling the propery `UseCookies` on the `HttpClientHandler` which is used for the `HttpClient` that is created in `Thinktecture.Relay.OnPremiseConnector.Net.Http.HttpClientFactory.CreateClient` the cookie is forwarded to the On-Premise application.

**Comment by gingters** [comment]
Closed by #329
