### ISSUE TITLE
Management Web --> max 10 Links displayed at the same time

### ISSUE THREAD

**Issue by pkuehnel** [thinktecture/relayserver#225]
### Actual behavior
The link overview in managamenetweb shows max 10 links at the same time. There is no way to show another page with another 10 links

### Expected behavior
There should be a feature with multiple pages and two buttons where you can go to the next/previous page

### Steps to reproduce
* Open Management Web on a Relay Server with more than 10 links  
  
or  

* Search for links in management web using a search term where you get more than 10 results

### Version
2.3.0.0-rc1

**Comment by gingters** [comment]
Thanks for creating this issue.

We are currently working on Relay v3 and at the moment we don't have plans to update or change the v2 management web.

In general, we suggest to automate RelayServer usage as much as possible by using the management api directly and not via the management web.

That said, if we'd get a pull request for the management web and it is concise, we'd be glad to review it.
