### ISSUE TITLE
Management Web --> Links table should be filterable for inactive links

### ISSUE THREAD

**Issue by pkuehnel** [thinktecture/relayserver#226]
### Actual behavior
There is no way to get all links which are currently not connected

### Expected behavior
The column with the red and green dots for active and inactive links should be filterable

### Steps to reproduce
* Open Management web --> Links
* The column which indicates if links are connected is not filterable

### Version
2.3.0.0-rc1

**Comment by gingters** [comment]
Thanks for creating this issue.

We are currently working on Relay v3 and at the moment we don't have plans to update or change the v2 management web.

In general, we suggest to automate RelayServer usage as much as possible by using the management api directly and not via the management web.

That said, if we'd get a pull request for the management web and it is concise, we'd be glad to review it.

**Comment by thomashilzendegen** [comment]
Closing due to the release of RelayServer 3.0.0, because no further development is done in the previous version anymore.
