### ISSUE TITLE
OnPremiseConnector crashes when timeout exceeded

### ISSUE THREAD

**Issue by gerry123** [thinktecture/relayserver#24]
maybe you could add a simple try catch like:

try
{
  await RequestOnPremiseTargetAsync(connector, onPremiseTargetRequest);
}
catch (Exception E)
{
  _logger.Error("UsefullErrorMessage: ", E);
  _logger.Trace("Please try to increase the timeout (current={0}s) in config (e.g. <relayServer baseUrl=\"...\" timeout=\"00:03:00\">)", _requestTimeout);
  return;
}

in ...\Thinktecture.Relay.OnPremiseConnector\SignalR\RelayServerConnection.cs OnReceived

greetings Gerhard

**Comment by michelmoorlag** [comment]
When the password is incorrect the connector crashes on a unhandeled: System.Exception: 'Could not authenticate with relay server: invalid_grant'

**Comment by ManuelRauber** [comment]
@michelmoorlag Can you open another issue for that?

**Comment by michelmoorlag** [comment]
@ManuelRauber: Done

**Comment by gingters** [comment]
This is resolved in the 2.0 release.
