### ISSUE TITLE
Add rabbit configuration to docs

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#265]
It was decided that RabbitMQ specific settings (i.e. queue or even message-specific TTL settings) should not be done in the Rabbit configuration section of the relay server transport, but in RabbitMQ directly via policies.

See also rabbit policy documentation https://www.rabbitmq.com/ttl.html

Reason:
This would create a leaky abstraction over an external system. Also, we would need to pass through all rabbit-specific settings 1:1, if rabbit adds or remove settings, we would need to adopt to these changes.
When configuring this directly in rabbit, this makes handling much easier.
Also, settings can be changed at runtime with rabbit policies.
Default policies can be provided as a script that only needs to be executed once.

**Comment by thomashilzendegen** [comment]
These information should be known by the operator of the RabbitMQ system/cluster already. We do not want to duplicate the documentation or give any suggestions about these values, as they are dependent on the scenario.
