### ISSUE TITLE
Azure supported?

### ISSUE THREAD

**Issue by michelmoorlag** [thinktecture/relayserver#30]
I would like to host this relay server on Azure to relay requests to an on-premise rest api. Azure has SQL server and RabbitMQ support so I wonder if this would be possible or has been done before? I would like to host the relay server as Azure WebJob.

**Comment by gingters** [comment]
This setup is not really recommended, and as such we did not test that scenario. From the Azure point of view, a WebJob is not really meant to host a windows service. We highly recommend using a VM instead, if you want to host the RelayServer on Azure.

That said, in theory it still could work. You probably just have to set the WebJob to always on and configure the connection string to the database and to the message queue accordingly.

**Comment by michelmoorlag** [comment]
For Rabbitmq I will need a vm anyway so I might as well use a windows server vm and host it all there. I will follow your recommendation, thanks.
