### ISSUE TITLE
Web gui not up to date

### ISSUE THREAD

**Issue by michelmoorlag** [thinktecture/relayserver#31]
I followed all (google translated) [instructions](https://github.com/thinktecture/relayserver/blob/master/Documentation/de/3-installation.md) and installed the latest 1.0.4 relay server on a azure vm. The most important relaying part works as aspected and is really nice. The issue is that the web gui not always seems up to date. After I log in the link and user screens show no data. After entering the screen again I can see data but they are not always up to date. For example the connections status is not correct. When I click the header to sort sometimes it shows the correct data sometimes not. The same for the logs tab, I don't always see the latest records even after pressing the refresh button.
The expected behavior is that I would always see the latest correct information.

**Comment by gingters** [comment]
Thank you for the report.

We already have plans for a general overhaul of the management UI, but we don't have a timeline yet.

**Comment by michelmoorlag** [comment]
Thank you for the quick response. It is not the most important issue but in a production situation it would be nice if the information is up to date.

**Comment by gingters** [comment]
Just a quick update here, since this issue had its first birthday: This will not be resolved in the current AngularJS version of the management web anymore, but in the upcoming rewrite. Good news is, a colleague already started with that rewrite. Bad news is, we still don't really have a timeline for when we want that to be completed.

**Comment by gingters** [comment]
v3 might get another management ui
