### ISSUE TITLE
Add Microsoft.CodeAnalysis.NetAnalyzers to all projects

### ISSUE THREAD

**Issue by thomashilzendegen** [thinktecture/relayserver#317]

**Comment by BorisWilhelms** [comment]
Die "Standard" dotnet Analyzer muessen nicht mehr installiert werden, sie sind nun beim SDK dabei und muessen nur aktiviert werden.

Die Anlayzer koennen mittels folgenden Properties (z.b. in der Directory.Build.props) aktiviert werden:

```
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
```

Diese Einstellungen erzeugen sehr viele Warnings. Ggfs. ueberpruefen welche Warnings sinnvoll sind.

Weitere Infos:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options?view=vs-2022
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#code-analysis-properties
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories?view=vs-2022

**Comment by BorisWilhelms** [comment]
Noch eine Info: Rider support dafuer ist meh. Wird nur in den Build-Warnings aber nicht im Editor direkt angezeigt....

**Comment by thomashilzendegen** [comment]
Nope.
