### ISSUE TITLE
Feature request: incorperate ACME client

### ISSUE THREAD

**Issue by michelmoorlag** [thinktecture/relayserver#32]
When running the relay server in production it really needs to run with https and therefore you need a certificate. With letsencrypt these are free today. Since the relay server is not running in IIS but is a selfhosting owin application you need to request and renew a certificate manually which is a pain in the a**. There is a .net library which support the ACME protocol to automate this process called [ACMESharp](https://github.com/ebekker/ACMESharp). Wouldn't it be nice if there was an extra web page where you could request and maintain a letsencrypt certificate using the ACME protocol?

**Comment by gingters** [comment]
First of all, sorry for having that unanswered for over a year. This is indeed a really good idea, and we'd love to incorporate that in one of the upcoming versions.

**Comment by thomashilzendegen** [comment]
Closing due to the release of RelayServer 3.0.0, because no further development is done in the previous version anymore.
