### ISSUE TITLE
Consolidate logging

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#377]
Make logging similar to what is done in .NET:

One nested `Log` class with all `[LoggerMessage]` definitions on it. EventId is counted from 1 per logging class.
Logging class is either scoped per project or even per single class when there are a lot of messages.

Examples: See HttpConnectionDispatcher.Log and HttpConnectionManager.Log in SignalR Core.

**Comment by gingters** [comment]
Also, while at it, add a scope (`ILogger.BeginScope`) to all endpoints (RelayMiddleware, Body endpoint) that adds at least the `RelayRequestId` (see #402 ) to the scope.

That way, internal logs (i.e. EF) will also add the RelayRequestId to the logging system.

**Comment by gingters** [comment]
We decided to make the EventId unique per project in an internal static class just like this:
https://github.com/dotnet/aspnetcore/blob/0684c8aa38c6b9926bae3d901741a83c453dc413/src/Servers/HttpSys/src/LoggerEventIds.cs

We then create a partial class for all LoggerMessages on each type: `{ClassName}.Log.cs` like this:
https://github.com/dotnet/aspnetcore/blob/0684c8aa38c6b9926bae3d901741a83c453dc413/src/Servers/HttpSys/src/HttpSysListener.Log.cs#L12

Usage is then like this:
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/HttpSys/src/HttpSysListener.cs#L238

**Comment by thomashilzendegen** [comment]
We should also solve the todos regarding https://github.com/dotnet/runtime/issues/69490 as this is fixed already.
