### ISSUE TITLE
Inconsistent timeouts for requests on server and connector?

### ISSUE THREAD

**Issue by gingters** [thinktecture/relayserver#405]
The `RequestExpiration` on the server options defaults to 10 seconds and is used to time out the request from the client on the server.

This means when the whole request takes longer than 10 seconds, the client's request is aborted on the server.

On the other hand, the default timeout for requests on the connector to the target (on the connector options) defaults to 100 seconds if not set (see `RelayTargetRegistry:139`).

Should we increase the RequestExpiration to at least 105 seconds? This should include margin for some slow round-trip-time to the connector, let that timeout and return the timeout response from there instead of timing out at the server a bit early.

**Comment by thomashilzendegen** [comment]
Fair point. We should introduce the following defaults:

`RequestExpiration` to 120 seconds.
`TargetTimeout` to 100 seconds.
