### ISSUE TITLE
The expected client_id in the token isn't the tenant id (guid)

### ISSUE THREAD

**Issue by thomashilzendegen** [thinktecture/relayserver#451]
We currently misuse the client_id as a guid (the tenant id). This is not correct.

Two examples to prove this:

https://github.com/IdentityServer/IdentityServer4/blob/4dc10e665f5ede63274427036c25cdc216130eb9/docs/topics/resources.rst#authorization-based-on-scopes

In that documentation, you see that the client_id is the alphanumeric username used to login (e.g., client credential flow where the client_id form field holds the username, too). Also, the "real unique" identifier of the user is held in the "sub" – in that example, a simple number because the client table's primary key is an integer.

The second example is the keycloak server. This server provides in the client_id the entered client_id in the management interface as expected. Also, it provides a guid in the "sub", representing the "real unique" identifier of the user.

In the end, the RFC states this also very clear:

https://www.rfc-editor.org/rfc/rfc7662#section-2.2

> client_id
OPTIONAL.  Client identifier for the OAuth 2.0 client that requested this token.

> sub
OPTIONAL.  Subject of the token, as defined in JWT [[RFC7519](https://www.rfc-editor.org/rfc/rfc7519)].
Usually a machine-readable identifier of the resource owner who authorized this token.

**Comment by gingters** [comment]
Closed by #452
