### ISSUE TITLE
Redirect in XHR for first-time setup does not work on IE or Edge

### ISSUE THREAD

**Issue by thomashilzendegen** [thinktecture/relayserver#8]
Nothing happens...

**Comment by gingters** [comment]
I can also reproduce this.
After the request to `/needsfirsttimesetup` in Edge the redirect to the first time setup page is not done.

**Comment by michelmoorlag** [comment]
I experienced the same issue.

**Comment by gingters** [comment]
This issue has been documented for the time being.
Please do the initial setup in Chrome or Firefox. This will be resolved with the Managemet-UI re-write, but not anymore in the current AngularJs version.
